plugins {
    id 'java'
}

group 'Flaviu_Florea.MPP.Swimming_Contest.Java'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project (':ContestModel')
    runtimeOnly group: 'org.xerial', name: 'sqlite-jdbc', version: '3.16.1'
    implementation 'org.springframework:spring-context:4.3.8.RELEASE'


    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'

    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.10.0'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.10.0'
    implementation 'org.hibernate:hibernate-core:5.3.20.Final'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.13.1'
}

test {
    useJUnitPlatform()
}