enum ThesisRequestStatus  {
    PENDING = "PENDING",
    PROFESSOR_ACCEPTED = "PROFESSOR_ACCEPTED",
    PROFESSOR_DECLINED  = "PROFESSOR_DECLINED",
    STUDENT_ACCEPTED = "STUDENT_ACCEPTED",
    STUDENT_DECLINED = "STUDENT_DECLINED",
    OUTDATED = "OUTDATED"
}

export default ThesisRequestStatus;